### ISSUE TITLE
Enhance Portal Berita UI with Blue Theme and Animations

### ISSUE THREAD

**Issue by Farkhansyah** [Farkhansyah/belajar-git#1]
### Color Scheme Updates
- Replace current gradient with blue-focused gradient scheme
- Update accent colors to match blue theme
- Implement consistent color variables for maintainability

### Animation Enhancements
1. Add smooth transitions for:
   - Navigation menu hover states
   - Search box focus
   - Social media icon interactions
   - Sidebar menu open/close
   - Content card hover effects
   - Widget loading animations

2. Header Improvements:
   - Animated logo
   - Smooth sticky header transition
   - Enhanced search bar interaction

3. Content Section Updates:
   - Card hover effects
   - Lazy load animations
   - Smooth transitions between pages

#### Update CSS Variables
```css
:root {
  --primary-blue: #0052cc;
  --secondary-blue: #0747a6;
  --accent-blue: #4c9aff;
  --hover-blue: #0065ff;
  --light-blue: #deebff;
  --text-dark: #172b4d;
  --text-light: #ffffff;
}
```

#### Add New Styles
```css
/* Animation Keyframes */
@keyframes fadeIn {
  from { opacity: 0; transform: translateY(20px); }
  to { opacity: 1; transform: translateY(0); }
}

@keyframes slideIn {
  from { transform: translateX(-100%); }
  to { transform: translateX(0); }
}

/* Updated Header Styles */
.header-top {
  background: linear-gradient(135deg, var(--primary-blue) 0%, var(--secondary-blue) 100%);
  transition: all 0.3s ease;
}

/* Enhanced Navigation */
.nav-menu a {
  position: relative;
  overflow: hidden;
}

.nav-menu a::after {
  content: '';
  position: absolute;
  bottom: 0;
  left: 0;
  width: 100%;
  height: 3px;
  background-color: var(--accent-blue);
  transform: translateX(-100%);
  transition: transform 0.3s ease;
}

.nav-menu a:hover::after {
  transform: translateX(0);
}

/* Content Cards Animation */
.content-card {
  animation: fadeIn 0.6s ease-out;
  transition: transform 0.3s ease, box-shadow 0.3s ease;
}

.content-card:hover {
  transform: translateY(-5px);
  box-shadow: 0 4px 20px rgba(0,0,0,0.15);
}

/* Widget Enhancements */
.widget {
  animation: fadeIn 0.6s ease-out;
  transition: transform 0.3s ease;
}

.widget:hover {
  transform: translateY(-3px);
}

/* Social Icons Animation */
.social-icons a {
  transition: all 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275);
}

.social-icons a:hover {
  transform: scale(1.2) translateY(-5px);
}

/* Search Box Enhancement */
.search-box input {
  transition: all 0.3s ease;
  border: 2px solid transparent;
}

.search-box input:focus {
  border-color: var(--accent-blue);
  box-shadow: 0 0 10px rgba(76,154,255,0.3);
}

/* Sidebar Animation */
.sidebar-overlay {
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
}

.sidebar-menu a {
  transition: all 0.3s ease;
  position: relative;
}

.sidebar-menu a::before {
  content: '';
  position: absolute;
  left: 0;
  top: 0;
  height: 100%;
  width: 3px;
  background-color: var(--primary-blue);
  transform: scaleY(0);
  transition: transform 0.3s ease;
}

.sidebar-menu a:hover::before {
  transform: scaleY(1);
}
```

### JavaScript Enhancements
- Add smooth scrolling
- Implement intersection observer for content animation
- Enhanced menu transitions

### Additional Features
1. Loading skeleton for content
2. Smooth page transitions
3. Scroll-to-top button
4. Enhanced mobile responsiveness

### Accessibility Improvements
- Ensure color contrast meets WCAG standards
- Add focus states for keyboard navigation
- Include ARIA labels where needed

### Performance Considerations
- Use CSS transforms for animations
- Implement will-change property where needed
- Optimize transition properties
